apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    name: mysql
    app: roar-db
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: roar-db
  replicas: {{ .Values.db.replicas }}
  template:
    metadata:
      labels:
        name: mysql
        app: roar-db
    spec:
      containers:
      - name: mysql
        image: {{ .Values.db.image }}
        ports:
        - name: mysql
          containerPort: 3306
        env:
          - name: MYSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                name: mysql-configmap
                key: mysql.database
          - name: MYSQL_PASSWORD
            valueFrom: 
              secretKeyRef:
                name: mysqlsecret
                key: mysqlpassword
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysqlsecret
                key: mysqlrootpassword
          - name: MYSQL_USER
            valueFrom:
              configMapKeyRef:
                name: mysql-configmap
                key: mysql.user
        volumeMounts:
          - name: mysql-storage
            mountPath: /var/lib/mysql
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: roar-mysql-pvc  # ← Changé de "mysql-pvc" à "roar-mysql-pvc"
