apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    name: mysql
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: "mysql"
    port: {{ .Values.db.service.port }}
    targetPort: {{ .Values.db.service.targetPort }}
  selector:
    name: mysql
