apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: roar-mysql-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.mysql.size }}
  storageClassName: {{ .Values.persistence.mysql.storageClass }}
