apiVersion: v1
kind: PersistentVolume
metadata:
  name: roar-mysql-pv
spec:
  capacity:
    storage: {{ .Values.persistence.mysql.size }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: {{ .Values.persistence.mysql.reclaimPolicy }}
  storageClassName: {{ .Values.persistence.mysql.storageClass }}
  hostPath:
    path: {{ .Values.persistence.mysql.hostPath }}
