apiVersion: v1
kind: Service
metadata:
  name: roar-web
  labels:
    name: roar-web
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.web.service.type }}
  ports:
  - port: {{ .Values.web.service.port }}
    targetPort: {{ .Values.web.service.targetPort }}
    {{- if eq .Values.web.service.type "NodePort" }}
    nodePort: {{ .Values.web.service.nodePort }}
    {{- end }}
  selector:
    name: roar-web
