apiVersion: v1
kind: Service
metadata:
  labels:
    app: result
  name: result
spec:
  type: {{ .Values.result.service.type }}
  ports:
  - name: "result-service"
    port: {{ .Values.result.service.port }}
    targetPort: {{ .Values.result.service.targetPort }}
    {{- if eq .Values.result.service.type "NodePort" }}
    nodePort: {{ .Values.result.service.nodePort }}
    {{- end }}
  selector:
    app: result
